### ISSUE TITLE
Is this still the recommended way to work with vue and onsenui?

### ISSUE THREAD

**Issue by rlam3** [superpikar/onsenui-vue-router-pwa#1]
Is this still the recommended way to work with vue and onsenui?

I've come across this article stating that it is unnecessary to use router now... 
https://onsen.io/blog/vue-2-onseui-beta-release/

Was wondering what your thoughts on this was. Thanks!

**Comment by superpikar** [comment]
> I've come across this article stating that it is unnecessary to use router now...
> https://onsen.io/blog/vue-2-onseui-beta-release/

@rlam3 the announcement mention about `Onsen UI already provides components for simple and yet powerful routing based on push/pop.`, use different approach than vue-router. 

The reason why I use vue-router in my app is since I want to build a mobile web app, the user has to be able to access URL via a browser address bar. 

If you look at onsenui-vue official example https://onsenui.github.io/vue-onsenui-kitchensink/main.html, whenever you open the page, the URL in browser address bar doesn't change. Also, you cannot open a specific page via browser address bar.

Also, keep in mind when you use vue-router, you need to implement the animation transition by yourself.

So I think it depends on your requirement whether you have to use onsenui-router or vue-router

Hope it helps :smile:

**Comment by rlam3** [comment]
@superpikar Thanks for your insight. When you talk about mobile web apps. are you talking about PWA? Not hybrid apps right? If I wanted to make hybrid apps deployable to iOS or android environment. Do you suggest I use OnsenUI router?

**Comment by superpikar** [comment]
Hello @rlam3,

My mobile web app is not a PWA yet. A little background, I work in South Korea, where most of the mobile app is a mobile web wrapped in android/ios native app.

For your case, I suggest you do a research first whether your app requirement needs a feature for push notification then go a certain route. Because it seems a bit complicated to accomplish if using `onsenui-router`. Meanwhile, it's easier if you're using `vue-router`, you only need to call below code to go a certain route
```
this.$router.push({ name: 'router-name'});
```

Fran Dios @frandiox made a good example of how to combine `vue-router` with `v-ons-navigator` to keep maintaining `popPage` and `pushPage` transition. Have a look https://github.com/frandiox/onsenui-vue-router/blob/master/src/App.vue
